
// This file has been generated by the GUI designer. Do not modify.
namespace RPiPlotter.Windows
{
	public partial class PreviewWindow
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.Image previewImage;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget RPiPlotter.Windows.PreviewWindow
			this.Name = "RPiPlotter.Windows.PreviewWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Preview");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child RPiPlotter.Windows.PreviewWindow.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.previewImage = new global::Gtk.Image ();
			this.previewImage.Name = "previewImage";
			w1.Add (this.previewImage);
			this.GtkScrolledWindow.Add (w1);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
